"""Auto-generated by arth. DO NOT EDIT."""
from collections import OrderedDict
from enum import Enum

from arth.ast import TypeKind, ArthPrimitive, StructType, OptionalType, NamedType, ArrayType, MapType, UnionType, UnionValue
from arth.base import BasePrimitive, BaseStruct, BaseUnion, initializer


LoginRequest = type("LoginRequest", (BaseStruct,), dict(_ast=StructType(OrderedDict(user_id=ArthPrimitive(TypeKind.U64), device=ArthPrimitive(TypeKind.U64), signature=ArrayType(ArthPrimitive(TypeKind.U8), 64))), __init__=initializer(('user_id', 'device', 'signature')), __doc__='LoginRequest: struct{\n    user_id: unsigned integer\n    device: unsigned integer\n    signature: array<unsigned integer>[64]\n}'))
LoginResponse = type("LoginResponse", (BasePrimitive,), dict(_ast=ArthPrimitive(TypeKind.Void), __doc__='LoginResponse: void type'))
RegisterRequest = type("RegisterRequest", (BaseStruct,), dict(_ast=StructType(OrderedDict(username=ArthPrimitive(TypeKind.String), auth_key=ArrayType(ArthPrimitive(TypeKind.U8), 32), device_key=ArrayType(ArthPrimitive(TypeKind.U8), 32), display_name=ArthPrimitive(TypeKind.String))), __init__=initializer(('username', 'auth_key', 'device_key', 'display_name')), __doc__='RegisterRequest: struct{\n    username: string\n    auth_key: array<unsigned integer>[32]\n    device_key: array<unsigned integer>[32]\n    display_name: string\n}'))
RegisterResponse = type("RegisterResponse", (BaseStruct,), dict(_ast=StructType(OrderedDict(user_id=ArthPrimitive(TypeKind.U64))), __init__=initializer(('user_id',)), __doc__='RegisterResponse: struct{\n    user_id: unsigned integer\n}'))
LookupRequest = type("LookupRequest", (BaseStruct,), dict(_ast=StructType(OrderedDict(username=ArthPrimitive(TypeKind.String))), __init__=initializer(('username',)), __doc__='LookupRequest: struct{\n    username: string\n}'))
LookupResponse = type("LookupResponse", (BaseStruct,), dict(_ast=StructType(OrderedDict(user_id=ArthPrimitive(TypeKind.U64), salt=ArrayType(ArthPrimitive(TypeKind.U8), 32))), __init__=initializer(('user_id', 'salt')), __doc__='LookupResponse: struct{\n    user_id: unsigned integer\n    salt: array<unsigned integer>[32]\n}'))
SendMessage = type("SendMessage", (BaseStruct,), dict(_ast=StructType(OrderedDict(channel=ArthPrimitive(TypeKind.U64), message=ArthPrimitive(TypeKind.String))), __init__=initializer(('channel', 'message')), __doc__='SendMessage: struct{\n    channel: unsigned integer\n    message: string\n}'))
TextMessage = type("TextMessage", (BaseStruct,), dict(_ast=StructType(OrderedDict(channel=ArthPrimitive(TypeKind.U64), user=ArthPrimitive(TypeKind.U64), stamp=ArthPrimitive(TypeKind.U64), message=ArthPrimitive(TypeKind.String))), __init__=initializer(('channel', 'user', 'stamp', 'message')), __doc__='TextMessage: struct{\n    channel: unsigned integer\n    user: unsigned integer\n    stamp: unsigned integer\n    message: string\n}'))
Befriend = type("Befriend", (BaseStruct,), dict(_ast=StructType(OrderedDict(user=ArthPrimitive(TypeKind.U64))), __init__=initializer(('user',)), __doc__='Befriend: struct{\n    user: unsigned integer\n}'))
Unfriend = type("Unfriend", (BaseStruct,), dict(_ast=StructType(OrderedDict(user=ArthPrimitive(TypeKind.U64))), __init__=initializer(('user',)), __doc__='Unfriend: struct{\n    user: unsigned integer\n}'))
